<a href="https://colab.research.google.com/github/DarkPrinceWarrior/Reuters-dataset-multiple-classification/blob/main/Reuters_predict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
from keras.datasets import reuters

In [11]:
(train_data, train_labels),(test_data, test_labels) = reuters.load_data(num_words=10000)

In [12]:
import numpy as np

def data_vectorize(sequence, dimension = 10000):
  results = np.zeros((len(sequence),dimension))
  for index, sequence in enumerate(sequence):
    results[index,sequence] = 1
  return results


x_train = data_vectorize(train_data)
x_test = data_vectorize(test_data)

In [13]:
def label_vectorize(label_sequence, dimension = 46):
  results = np.zeros((len(label_sequence),dimension))
  for index, label in enumerate(label_sequence):
    results[index,label] = 1
  return results


one_hot_train_labels =label_vectorize(train_labels)
one_hot_test_labels = label_vectorize(test_labels)

In [ ]:
# the same way but with embeded function in Keras
# from keras.utils.np_utils import to_categorical
# one_hot_train_labels = to_categorical(train_labels)
# one_hot_test_labels = to_categorical(test_labels)

# another way to convert labels
# y_train = np.array(train_labels)
# y_test = np.array(test_labels)
# in this way when compiling the model with integers labels
# should be used loss function = "sparse_categorical_crossentropy" 



In [9]:
from keras import models 
from keras import layers

model = models.Sequential()
model.add(layers.Dense(64, activation="relu", input_shape=(10000,)))
model.add(layers.Dense(64,activation="relu"))
model.add(layers.Dense(46,activation="softmax"))


In [14]:
model.compile(
    optimizer = "rmsprop",
    loss = "categorical_crossentropy",
    metrics = ['accuracy'])


In [15]:
x_val = x_train[:1000]
partial_x_train = x_train[1000:]

y_val = one_hot_train_labels[:1000]
partial_y_train = one_hot_train_labels[1000:]


In [18]:
history = model.fit(
    partial_x_train,
    partial_y_train,
    epochs = 20,
    batch_size = 512,
    validation_data=(x_val,y_val) )

Epoch 1/20
16/16 [==============================] - 2s 70ms/step - loss: 2.6323 - accuracy: 0.4881 - val_loss: 1.7571 - val_accuracy: 0.6000
Epoch 2/20
16/16 [==============================] - 1s 51ms/step - loss: 1.4387 - accuracy: 0.6918 - val_loss: 1.3033 - val_accuracy: 0.7070
Epoch 3/20
16/16 [==============================] - 1s 50ms/step - loss: 1.0563 - accuracy: 0.7729 - val_loss: 1.1460 - val_accuracy: 0.7440
Epoch 4/20
16/16 [==============================] - 1s 49ms/step - loss: 0.8304 - accuracy: 0.8236 - val_loss: 1.0407 - val_accuracy: 0.7790
Epoch 5/20
16/16 [==============================] - 1s 49ms/step - loss: 0.6608 - accuracy: 0.8603 - val_loss: 0.9558 - val_accuracy: 0.8020
Epoch 6/20
16/16 [==============================] - 1s 50ms/step - loss: 0.5282 - accuracy: 0.8874 - val_loss: 0.9262 - val_accuracy: 0.8070
Epoch 7/20
16/16 [==============================] - 1s 49ms/step - loss: 0.4246 - accuracy: 0.9109 - val_loss: 0.8867 - val_accuracy: 0.8150
Epoch 8/20
16

In [19]:
model = models.Sequential()
model.add(layers.Dense(64, activation="relu", input_shape=(10000,)))
model.add(layers.Dense(64,activation="relu"))
model.add(layers.Dense(46,activation="softmax"))



In [20]:
model.compile(
    optimizer = "rmsprop",
    loss = "categorical_crossentropy",
    metrics = ['accuracy'])

In [21]:
model.fit(
    partial_x_train,
    partial_y_train,
    epochs = 9,
    batch_size = 512,
    validation_data=(x_val,y_val) )


Epoch 1/9
16/16 [==============================] - 2s 66ms/step - loss: 2.7093 - accuracy: 0.4965 - val_loss: 1.8172 - val_accuracy: 0.6180
Epoch 2/9
16/16 [==============================] - 1s 49ms/step - loss: 1.4754 - accuracy: 0.7066 - val_loss: 1.3370 - val_accuracy: 0.7130
Epoch 3/9
16/16 [==============================] - 1s 48ms/step - loss: 1.0771 - accuracy: 0.7780 - val_loss: 1.1562 - val_accuracy: 0.7510
Epoch 4/9
16/16 [==============================] - 1s 47ms/step - loss: 0.8436 - accuracy: 0.8218 - val_loss: 1.0388 - val_accuracy: 0.7810
Epoch 5/9
16/16 [==============================] - 1s 48ms/step - loss: 0.6661 - accuracy: 0.8641 - val_loss: 0.9659 - val_accuracy: 0.8040
Epoch 6/9
16/16 [==============================] - 1s 48ms/step - loss: 0.5295 - accuracy: 0.8887 - val_loss: 0.9226 - val_accuracy: 0.8110
Epoch 7/9
16/16 [==============================] - 1s 49ms/step - loss: 0.4243 - accuracy: 0.9126 - val_loss: 0.8978 - val_accuracy: 0.8170
Epoch 8/9
16/16 [===

In [22]:
results = model.evaluate(x_test,one_hot_test_labels)

71/71 [==============================] - 0s 3ms/step - loss: 1.0144 - accuracy: 0.7827


In [32]:
# random probability prediction of right classified labels
import copy 

print(test_labels[:5])
test_labels_copy = copy.copy(test_labels)
np.random.shuffle(test_labels_copy)
print(test_labels[:5])
print(test_labels_copy[:5])
print(np.array(test_labels[:5]) == np.array(test_labels_copy[:5]))


[19  3 13 20  3]
[19  3 13 20  3]
[ 4  3  3  3 11]
[False  True False False False]


In [33]:
predictions = model.predict(x_test)

In [44]:
# the probability of topic possesed to specific news
a = 0
index1 = 0
for index,value in enumerate(predictions[1]):
  if a < value:
    a = value
    index1 = index
  if index == len(predictions[1])-1:
    print(index1)

# another variant
print(np.argmax(predictions[1]))

10
10
